---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "demo-app"
  namespace: "default"
  labels:
    app: "demo-app"
    version: "v1"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "demo-app"
      version: "v1"
  template:
    metadata:
      labels:
        app: "demo-app"
        version: "v1"
    spec:
      containers:
      - name: "demo-app-1"
        image: "amoghaj/demo-app:v1"
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "demo-app-service"
  namespace: "default"
  labels:
    app: "demo-app"
    version: "v1"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080
  selector:
    app: "demo-app"
    version: "v1"
  type: "LoadBalancer"
