---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "demo-app-v2"
  namespace: "default"
  labels:
    app: "demo-app"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "demo-app"
      version: "v2"
  template:
    metadata:
      labels:
        app: "demo-app"
        version: "v2"
    spec:
      containers:
      - name: "demo-app-v2"
        image: "amoghaj/demo-app:v2"
        ports:
        - name: http
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: http
          periodSeconds: 5