---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "demo-app-service"
  namespace: "default"
  labels:
    app: "demo-app"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080
  selector:
    app: "demo-app"
  type: "LoadBalancer"